steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['ci']
    
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/kissthem', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/kissthem']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'kissthem'
      - '--image'
      - 'gcr.io/$PROJECT_ID/kissthem'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
      - '--service-account'
      - '123679151422-compute@developer.gserviceaccount.com'

images:
  - 'gcr.io/$PROJECT_ID/kissthem'

options:
  logging: CLOUD_LOGGING_ONLY 